export enum DayOfWeek {
  MONDAY = 0,
  TUESDAY,
  WEDNESDAY,
  THURSDAY,
  FRIDAY,
  SATURDAY,
  SUNDAY,
}

export enum Degree {
  BACHELOR = 'BACHELOR',
  BACHELOR_CONTINUE = 'BACHELOR_CONTINUE',
  BACHELOR_INTER = 'BACHELOR_INTER',
  PUNDIT = 'PUNDIT',
  PUNDIT_INTER = 'PUNDIT_INTER',
}

export enum WorkloadType {
  LECTURE = 'LECTURE',
  LAB = 'LAB',
}
